# Generated by Django 5.2 on 2026-05-09 22:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('slug', models.SlugField(blank=True, help_text='Se genera automáticamente a partir del nombre.', max_length=120, unique=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('captura', 'Captura'), ('revision', 'Revisión'), ('publicada', 'Publicada')], max_length=20, unique=True, verbose_name='Nombre del estatus')),
            ],
            options={
                'verbose_name': 'Estatus',
                'verbose_name_plural': 'Estatus',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/%Y/', verbose_name='Foto de perfil')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('redactor', 'Redactor'), ('lector', 'Lector')], default='lector', max_length=20, verbose_name='Rol')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('contenido', models.TextField(help_text='Contenido completo de la publicación (LongText en la BD).', verbose_name='Contenido')),
                ('resumen', models.CharField(blank=True, help_text='Breve extracto que aparece en las tarjetas de noticias.', max_length=300, verbose_name='Resumen / Extracto')),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='publicaciones/imagenes/%Y/%m/', verbose_name='Imagen destacada')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('vistas', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='core.categoria', verbose_name='Categoría')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='core.estatus', verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del archivo')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word (.docx)'), ('excel', 'Excel (.xlsx)'), ('imagen', 'Imagen'), ('otro', 'Otro')], default='otro', max_length=10, verbose_name='Tipo')),
                ('archivo', models.FileField(upload_to='publicaciones/archivos/%Y/%m/', verbose_name='Archivo')),
                ('subido_en', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
                ('tamanio_bytes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='core.publicacion', verbose_name='Publicación')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-subido_en'],
            },
        ),
    ]
