# Generated by Django 5.2 on 2026-05-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fix_slug_maxlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono_css',
            field=models.CharField(blank=True, default='bi-tag', help_text='Ejemplo: bi-graph-up-arrow, bi-buildings, etc.', max_length=50, verbose_name='Icono (Bootstrap Icons)'),
        ),
    ]
