# Generated by Django 5.2 on 2026-05-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='usuario_nombre',
            field=models.CharField(blank=True, help_text='Copia denormalizada del nombre para visualización rápida en BD.', max_length=255, verbose_name='Nombre del usuario (DB View)'),
        ),
    ]
