# Generated by Django 5.2 on 2026-05-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comentario_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
