# Generated by Django 5.2 on 2026-05-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_publicacion_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen. Se usa si no se sube un archivo.', max_length=500, null=True, verbose_name='Imagen destacada (URL)'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen_destacada',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/imagenes/%Y/%m/', verbose_name='Imagen destacada (archivo)'),
        ),
    ]
