# Generated by Django 5.2 on 2026-05-26 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_publicacion_imagen_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='publicaciones/galeria/%Y/%m/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Útil si deseas ordenar las imágenes de la galería.', verbose_name='Orden')),
                ('subida_en', models.DateTimeField(auto_now_add=True, verbose_name='Subida el')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_imagenes', to='core.publicacion', verbose_name='Publicación')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Imágenes de Galería',
                'ordering': ['orden', 'subida_en'],
            },
        ),
    ]
