# Generated by Django 5.2 on 2026-05-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_galeriaimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriaimagen',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen para la galería.', max_length=500, null=True, verbose_name='Imagen (URL)'),
        ),
        migrations.AlterField(
            model_name='galeriaimagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/galeria/%Y/%m/', verbose_name='Imagen'),
        ),
    ]
